-- Phase 1F (RAG): in-process vector store. One embedding row per (hotel_id, sop_id).
-- The vector itself is a fixed-dimension CSV-serialized float array stored in a
-- TEXT column (no pgvector dependency yet; the same schema works on H2 and Postgres
-- so the Postgres datasource swap needs no code change). hotel_id enforces tenant
-- isolation at the data layer (AGENTS.md §8).

CREATE TABLE sop_embedding (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id      VARCHAR(64)  NOT NULL,
    sop_id        VARCHAR(64)  NOT NULL,
    content_hash  VARCHAR(64)  NOT NULL,
    embedding     CLOB         NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_sop_embedding_hotel_sop UNIQUE (hotel_id, sop_id)
);

CREATE INDEX ix_sop_embedding_hotel ON sop_embedding (hotel_id);
