-- Phase 1F (RAG, BRD §5): in-process vector store for uploaded KB documents.
-- One embedding row per (hotel_id, chunk_id). Mirrors V5__vector_store.sql but for
-- the document corpus instead of SOPs. Same schema works on H2 and Postgres so the
-- Postgres datasource swap needs no code change. hotel_id enforces tenant isolation
-- at the data layer (AGENTS.md §8).

CREATE TABLE document_embedding (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id      VARCHAR(64)  NOT NULL,
    chunk_id      VARCHAR(64)  NOT NULL,
    document_id   VARCHAR(64)  NOT NULL,
    content_hash  VARCHAR(64)  NOT NULL,
    embedding     CLOB         NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_document_embedding_hotel_chunk UNIQUE (hotel_id, chunk_id)
);

CREATE INDEX ix_document_embedding_hotel ON document_embedding (hotel_id);
CREATE INDEX ix_document_embedding_document ON document_embedding (document_id);
